### ISSUE TITLE
v1 does not exist

### ISSUE THREAD

**Issue by MeRuslan** [yc-actions/yc-cr-login#2]
[v0.1-alpha](https://github.com/yc-actions/yc-cr-login/releases/tag/v0.1-alpha) - единственный тэг, а в документации есть строка: 
`        uses: yc-actions/yc-cr-login@v1
`

**Comment by nikolaymatrosov** [comment]
https://github.com/yc-actions/yc-cr-login/releases/tag/v1.0.0
