### ISSUE TITLE
Error: Could not login: Error response from daemon: Get "https://cr.yandex/v2/"

### ISSUE THREAD

**Issue by r34son** [yc-actions/yc-cr-login#76]
Getting error:
`Error: Could not login: Error response from daemon: Get "https://cr.yandex/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

[CI logs](https://github.com/r34son/profile/actions/runs/9554559086/job/26336003644#step:9:32)

**Comment by nikolaymatrosov** [comment]
To resolve the issue you're encountering, please try restarting the pipeline. This can often resolve connection or timeout issues.
