### ISSUE TITLE
Error: Process completed with exit code 127.

### ISSUE THREAD

**Issue by joker2017** [yc-actions/yc-cr-login#8]
<img width="609" alt="image" src="https://github.com/yc-actions/yc-cr-login/assets/25124537/81757466-de2e-4ef8-b04a-43398dcdcf13">

Не работает, ругается на файлы sh. От всех sh избавился, всеравно ругается. Билдиксом на докер ком все заливается хорошо

<img width="683" alt="image" src="https://github.com/yc-actions/yc-cr-login/assets/25124537/6f00a6e6-af00-497c-8a43-b181a56f10cd">

**Comment by nikolaymatrosov** [comment]
В этом экшене не sh файлов. Скорее всего это какие-то ваши файлы. И значит проблму стоит искать там.
